title = "Virtually Potato"
baseurl = "https://virtuallypotato.com/"
paginate = 15
theme = ["hugo-cloak-email", "hugo-clarity"]
DefaultContentLanguage = "en"

[taxonomies]
  tag = "tags"
  series = "series"

[permalinks]
  posts = ":filename"

[outputs]
   home = ["HTML", "RSS","JSON"]
