title = "Virtually Potato"  
paginate = 10
theme = "hugo-clarity"
enableEmoji = true
DefaultContentLanguage = "en"

[taxonomies]
  tag = "tags"
  series = "series"

[permalinks]
  posts = ":filename"
