timeout = 30000
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[privacy]

[privacy.googleAnalytics]
disable = false
anonymizeIP = true
respectDoNotTrack = true

[privacy.vimeo]
disable = false
simple = true

[privacy.twitter]
disable = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.instagram]
disable = false
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true