## Metadata
twitter = "@johndotbowdre"
largeTwitterCard = true 
introDescription = "Wrangler of imaginary computers."
description = "I can generally fumble through a project and make it work. Here I share how I did it: my adventures with VMware vRealize Automation, cloud and automation projects I'm working on, linux and Powershell scripts I've cobbled together, and other tech tips and tricks."
since = 2018

## Logos & icons
fallBackOgImage = "logos/thumbnail.png"
iconsDir = "images/icons/"
centerLogo = false
logo = "logos/logo.png"
footerLogo = "logos/logo_footer.png"


## Site preferences
numberOfTagsShown = 10 
codeMaxLines = 25
codeLineNumbers = false
enableMathNotation = false
usePageBundles = true
mainSections = ["posts"] 
figurePositionShow = false 
mobileNavigation = "right" 
enforceLightMode = false
enforceDarkMode = true
titleSeparator = "-"
numberOfRecentPosts = 6
numberOfRelatedPosts = 6
numberOfFeaturedPosts = 4
toc = true

## Website author
[author]
  name = "John Bowdre"
  photo = "images/bio-photo.jpg" 

## Comments
comments = true
[utterances]
  repo="jbowdre/virtuallypotato" # owner/repo where github comments will happen
  issueterm="title" # how will the issues be mapped to the articles
  theme="dark-blue" # theme to be applied to comments box
