[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"

[context.production]
  command = "hugo"

[context.staging]
  command = "hugo --environment staging"
  [[headers]]
    for = "/*"
    [headers.values]
    X-Robots-Tag = "noindex"

[context.drafts]
  command = "hugo --environment drafts -D"
  [[headers]]
    for = "/*"
    [headers.values]
    X-Robots-Tag = "noindex"

[context.vanilla]
  command = "hugo --environment vanilla"
  [[headers]]
    for = "/*"
    [headers.values]
    X-Robots-Tag = "noindex"