[[main]]
  name = "vPotato"
  url = ""
  weight = -110

[[main]]
  name = "K8s on vSphere"
  url = "series/k8s-on-vsphere/"
  weight = -109

[[main]]
  name = "vRA 8"
  url = "series/vra8/"
  weight = -108

[[main]]
  name = "Projects"
  url = "series/projects/"
  weight = -107

[[main]]
  name = "Scripts"
  url = "series/scripts"
  weight = -106

[[main]]
  name = "Tips"
  url = "series/tips/"
  weight = -105

# Submenus
[[main]]
  name = "Connect"
  identifier = "Connect"
  weight = -100
[[main]]
  parent = "Connect"
  name = "Session"
  url = "/session/"
[[main]]
  parent = "Connect"
  name = "XMPP"
  url = "/xmpp/"
[[main]]
  parent = "Connect"
  name = "GitHub"
  url = "https://github.com/jbowdre"
[[main]]
  parent = "Connect"
  name = "CounterSocial"
  url = "https://counter.social/@john_b"

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/jbowdre"


[[social]]
  name = "rss"
  weight = 3
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"